name: Python Pull Request Workflow
on: [pull_request]
jobs:
 
 
  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
        
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      
      - name: Run unit tests
        run: |
          pip install pytest
          mkdir conf
          pytest
          
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.13.4
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}